[
{"name":"5 сантиметров в секунду",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"../page/5-santimetrov-v-secundu/5-santimetrov-v-secundu.html",
        "image":"../img/anime/5-santimetrov-v-secundu.jpg"},

{"name":"91 Days",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "wand":{"wood":"holly","core":"phoenix feather","length":11},
        "url":"",
        "image":"../img/anime/91-day.jpg"},

{"name":"Абсолютный дуэт",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "url":"",
        "image":"../img/anime/absolyutnyj-duet.jpg"},

{"name":"Агент Паранойи",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "url":"",
        "image":"../img/anime/agent-paranoi.jpg"},

{"name":"Дурочка",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "url":"",
        "image":"../img/anime/aho-girl.jpg"},

{"name":"Ангельские ритмы",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "url":"",
        "image":"../img/anime/angelskie-ritmy.jpg"},

{"name":"Иная",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/another.jpg"},

{"name":"Арифурэта: сильнейший ремесленник в мире",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/arifureta-silnejshij-remeslennik-v-mire.jpg"},

{"name":"Арифурэта: сильнейший ремесленник в мире 2",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/arifureta-silnejshij-remeslennik-v-mire-2.jpg"},

{"name":"Арифурэта: сильнейший ремесленник в мире (дополнительные эпизоды)",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "url":"",
        "image":"../img/anime/arifureta-silnejshij-remeslennik-v-mire-dopolnitelnye-epizody.jpg"},

{"name":"Атака титанов",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/ataka-titanov.jpg"},

{"name":"Атака титанов 2",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/ataka-titanov-2.jpg"},

{"name":"Атака титанов 3",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/ataka-titanov-3.jpg"},

{"name":"Атака титанов: без сожалений",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/ataka-titanov-bez-sozhalenij.jpg"},

{"name":"Атака титанов: дневник Илзе",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/ataka-titanov-dnevnik-ilze.jpg"},

{"name":"Атака титанов: потерянные девушки",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/ataka-titanov-poterjannye-devushki.jpg"},

{"name":"Атака титанов: финал",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "url":"",
        "image":"../img/anime/ataka-titanov-final.jpg"},

{"name":"Бездарная Нана",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/bezdarnaya-nana.jpg"},

{"name":"Бездомный бог",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/bezdomnyj-bog.jpg"},

{"name":"Бездомный бог: Арагото",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/bezdomnyj-bog-aragoto.jpg"},

{"name":"Бильярд смерти",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/biljard-smerti.jpg"},

{"name":"Чёрная пуля",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "url":"",
        "image":"../img/anime/black-bullet.jpg"},

{"name":"Кастелвания",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/castlevaniya.jpg"},

{"name":"Цельнометаллический алхимик",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/celostnometallicheskij-alhimik.jpg"},

{"name":"Цельнометаллический алхимик 2",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/celostnometallicheskij-alhimik-2.jpg"},

{"name":"Чёрный клевер",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "url":"",
        "image":"../img/anime/chernyj-klever.jpg"},

{"name":"Дневник будущего",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/dnevnik-budushego.jpg"},

{"name":"Дорога зверя",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/doroga-zverya.jpg"},

{"name":"Дороро",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/dororo.jpg"},

{"name":"Дюрарара!!",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "url":"",
        "image":"../img/anime/dyurarara.jpg"},
        
{"name":"Эхо террора",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/eho-terrora.jpg"},
        
{"name":"Эльфийская песнь",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "url":"",
        "image":"../img/anime/elfijskaja-pesn.jpg"},
        
{"name":"Этот глупый свин не понимает мечту девочки-зайки",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "url":"",
        "image":"../img/anime/etot-glupyj-svin-ne-ponimaet-mechtu-devochki-zajki.jpg"},
        
{"name":"Пламенная бригада пожарных",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/fire-force.jpg"},
        
{"name":"Форма голоса",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/forma-golosa.jpg"},
        
{"name":"Фури-кури",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/furi-kuri.jpg"},
        
{"name":"Врата",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/gate.jpg"},
        
{"name":"Врата 2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/gate-2.jpg"},
        
{"name":"Город актёров",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/gorod-akterov.jpg"},
        
{"name":"Город, в котором меня нет",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/gorod-v-kotorom-menja-net.jpg"},
        
{"name":"Госпожа Кагуя: В любви, как на войне",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/gospozha-kaguya-v-lyubvi-kak-na-voyne.jpg"},

{"name":"Госпожа Кагуя: В любви, как на войне 2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/gospozha-kaguya-v-lyubvi-kak-na-voyne-2.jpg"},

{"name":"Хантер х Хантер 1999",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/hanter-x-hanter-1999.jpg"},
        
{"name":"Хантер х Хантер: пилотная серия",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/hanter-x-hanter-pilotnaja-serija.jpg"},
        
{"name":"Ходячий замок",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/hodjachij-zamok.jpg"},
        
{"name":"Хоремия",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/horimiya.jpg"},
        
{"name":"ID:invaded",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/id-invaded.jpg"},
        
{"name":"Игра Дарвина",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/igra-darvina.jpg"},
        
{"name":"Инцидент кэмоно",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/incident-kemono.jpg"},
        
{"name":"Инуяшики",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/inujashiki.jpg"},
        
{"name":"Я хочу съесть твою поджелудочную",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/ja-hochu-sest-tvoju-podzheludochnuju.jpg"},
        
{"name":"Ямадо и 7 ведьм",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/jamado-i-7-vedm.jpg"},
        
{"name":"Как и ожидалось, моя школьная романтическая жизнь не удалась [ova-1]",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/kak-i-ozhidal-moja-shkolnaja-romanticheskaja-zhizn-ne-udolas-[ova-1].jpg"},
        
{"name":"Как и ожидалось, моя школьная романтическая жизнь не удалась",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/kak-i-ozhidal-moja-shkolnaja-romanticheskaja-zhizn-ne-udolas-[tv-1].jpg"},
        
{"name":"Кэнган Асура",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/kengan-asura.jpg"},
        
{"name":"Кэнган Асура 2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/kengan-asura.jpg"},
        
{"name":"Рубить Крамсать",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/kill-la-kill.jpg"},
        
{"name":"Класс убийц",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/klass-ubijc.jpg"},
        
{"name":"Класс убийц 2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/klass-ubijc-2.jpg"},
        
{"name":"Клинок рассекающий демонов",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/klinok-rassekajuschij-demonov.jpg"},
        
{"name":"Код Гиас: Восстание Лелуша",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/kod-gias-vosstanie-lelusha.jpg"},
        
{"name":"Код Гиас: Восстание Лелуша R2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/kod-gias-vosstanie-lelusha-r2.jpg"},
        
{"name":"Богиня благословляет этот прекрасный мир!",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/konosuba.jpg"},
        
{"name":"Богиня благословляет этот прекрасный мир 2!",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/konosuba-2.jpg"},
        
{"name":"Богиня благословляет этот прекрасный мир: багровая легенда",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/konosuba-bagrovaj-legenda.jpg"},
        
{"name":"Контроль",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/control.jpg"},
        
{"name":"Маг-целитель: Новый старт",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/mag-celitel-novyj-start.jpg"},
        
{"name":"Магическая битва",
        "type":"Аниме",
        "serial":true,
        "during":10,
        "time":0,
        "url":"",
        "image":"../img/anime/magicheskaya-bitva.jpg"},
        
{"name":"Моб психо 100",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/mob-psiho-100.jpg"},
        
{"name":"Моб психо 100 сезон 2",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/mob-psiho-100-2.jpg"},
        
{"name":"Моб психо 100: Путешествие, которое склеивает сердца и лечит душу",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/mod-psiho-100-puteshestvie-kotoroe-skleivaet-serdca-i-lechit-dushu.jpg"},
        
{"name":"Моя геройская академия",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/moja-gerojskaja-akademija.jpg"},
        
{"name":"Моя геройская академия 2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/moja-gerojskaja-akademija-2.jpg"},
        
{"name":"Моя геройская академия 3",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/moja-gerojskaja-akademija-3.jpg"},
        
{"name":"Моя геройская академия 4",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/moja-gerojskaja-akademija-4.jpg"},
        
{"name":"Моя геройская академия: Два героя",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/moja-gerojskaja-akademija-dva-geroja.jpg"},
        
{"name":"Необъятный океан",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/neobjatnyj-okean.jpg"},
        
{"name":"Непризнанный школой владыка демонов",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/nepriznannyj-shkoloj-vladyka-demonov.jpg"},
        
{"name":"Нет игры - нет жизни",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/net-igry-net-zhizni.jpg"},
        
{"name":"Нет игры - нет жизни: Начало",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/net-igry-net-zhizni-nachalo.jpg"},
        
{"name":"О моём перерождении в слизь",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/o-moem-pererozhdenii-v-sliz.jpg"},
        
{"name":"О моём перерождении в слизь 2 ",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/o-moem-pererozhdenii-v-sliz-2.jpg"},
    
{"name":"One Punch-man",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/one-punch-man.jpg"},
    
{"name":"One Punch-man [S]",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/one-punch-man-specvypusk.jpg"},

{"name":"One Punch-man 2",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/one-punch-man-2.jpg"},
    
{"name":"One Punch-man 2 [S]",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/one-punch-man-2-specvypusk.jpg"},
    
{"name":"One Punch-man: Путь к становлению героем",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/one-punch-man-put-k-stanovleniu-geroem.jpg"},
    
{"name":"Overlord",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/overlord.jpg"},
    
{"name":"Overlord 2",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/overlord-2.jpg"},
    
{"name":"Overlord 3",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/overlord-3.jpg"},
    
{"name":"Overlord: Бессмертный король",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/overlord-bessmertny-korol.jpg"},
    
{"name":"Overlord: Тёмный воитель",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/overlord-temny-voitel.jpg"},
    
{"name":"Парад смерти",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/parad-smerti.jpg"},
    
{"name":"Паразит: Учение о жизни",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/parazit-uchenie-o-zhizni.jpg"},
    
{"name":"Патэма наоборот",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/patema-naoborot.jpg"},
    
{"name":"Пикник в потусторонье",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/piknik-v-potustorone.jpg"},

{"name":"Призрачный мир мириады цветов",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/prizrachnyj-mir-miriady-cvetov.jpg"},

{"name":"Путешествие Элейн",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/puteshestvie-elejny.jpg"},

{"name":"Rainbow: семеро из шестой камеры",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/rainbow-semero-iz-shestoy-kamery.jpg"},

{"name":"Реинкарнация безработного: История о приключениях в другом мире",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/reinkarnaciya-bezrabotnogo-istoriya-o-priklyucheniyah-v-drugom-mire.jpg"},

{"name":"Повторная жизнь",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/relife.jpg"},

{"name":"re:zero",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/re-zero.jpg"},

{"name":"re-zero-[ova]",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/re-zero-[ova].jpg"},

{"name":"re-zero-2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/re-zero-2.jpg"},

{"name":"re:zero: Снежные воспоминания",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/re-zero-snezhnye-vospominanija.jpg"},

{"name":"Сакамото, а что?",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/sakamoto-a-chto.jpg"},

{"name":"Сатана на подработке",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/satana-na-podrabotke.jpg"},

{"name":"7 смертных грехов",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/sem-smertnyh-grehov.jpg"},

{"name":"7 смертных грехов 2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/sem-smertnyh-grehov-2.jpg"},

{"name":"7 смертных грехов: Узники небес",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/sem-smertnyh-grehov-uzniki-nebes.jpg"},

{"name":"Сердцу хочется кричать",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/serdcu-hochetsja-krichat.jpg"},

{"name":"Шерлок из Кабуки-тё",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/sherlok-iz-kabuki-te.jpg"},

{"name":"Школа-тюрьма",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/shkola-tjurma.jpg"},

{"name":"Школа-тюрьма: Мастерское скольжение",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/shkola-tjurma-masterskoe-skolzhenie.jpg"},

{"name":"Скитальцы",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/skitalcy.jpg"},

{"name":"Сквозь слёзы, я притворюсь кошкой",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/skvoz-slezy-ja-pritvorjajus-koshkoj.jpg"},

{"name":"Сладкая жизнь",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/sladkaya-zhizn.jpg"},

{"name":"Сомали и лесной дух",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/somali-i-lesnoj-duh.jpg"},

{"name":"Страна чудес смертников",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/strana-chudes-smertnikov.jpg"},

{"name":"Связанные болью",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/svjazannye-bolju.jpg"},

{"name":"Связанные небом",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/svjazannye-nebom.jpg"},

{"name":"Связь сердец: По случайному пути",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/svjaz-serdec-po-sluchajnomu-puti.jpg"},

{"name":"Тёмный дворецкий",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/temnyj-dvoreckij.jpg"},

{"name":"Тёмный дворецкий 2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/temnyj-dvoreckij-2.jpg"},

{"name":"Тёмный дворецкий: Глава об Атлантике",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/temnyj-dvoreckij-glava-ob-atlantike.jpg"},

{"name":"Тёмный дворецкий: Глава о цирке",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/temnyj-dvoreckij-glava-o-cirke.jpg"},

{"name":"Тетрадь смерти",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/tetrad-smerti.jpg"},

{"name":"Твоё имя",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/tvoe-imja.jpg"},

{"name":"Убийца Акаме",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/ubijca-akame.jpg"},

{"name":"Убийца гоблинов",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/ubijca-goblinov.jpg"},

{"name":"Убийца гоблинов: Корона гоблина",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/ubijca-goblinov-korona-goblina.jpg"},

{"name":"Убийца гоблинов 2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/ubijca-goblinov-2.jpg"},

{"name":"Укрась прощальное утро цветами обещания",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/ukras-proschalnoe-utro-cvetami-objaschanija.jpg"},

{"name":"Унесённые призраками",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/unesennye-prizrakami.jpg"},

{"name":"Ведьма за работой",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/vedma-za-rabotoj.jpg"},

{"name":"Ведьмина служба доставки",
        "type":"Аниме",
        "serial":false,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/vedmina-sluzhba-dostavki.jpg"},

{"name":"Волчица и пряности",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/volchica-i-prjanosti.jpg"},

{"name":"Волчица и пряности [ova]",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/volchica-i-prjanosti-ova.jpg"},

{"name":"Восхождение героя щита",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/voshozhdenie-geroja-schita.jpg"},

{"name":"В подземелье я пойду, там красавицу найду",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/v-podzemele-ja-pojdu-tam-krasavicu-najdu.jpg"},

{"name":"В подземелье я пойду, там красавицу найду [ova]",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/v-podzemele-ja-pojdu-tam-krasavicu-najdu-[ova].jpg"},

{"name":"В подземелье я пойду, там красавицу найду – Меч Оратории",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/v-podzemele-ja-pojdu-tam-krasavicu-najdu-mech-oratorii.jpg"},

{"name":"В подземелье я пойду, там красавицу найду - Стрела Ориона",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/v-podzemele-ja-pojdu-tam-krasavicu-najdu-strela-oriona.jpg"},

{"name":"В подземелье я пойду, там красавицу найду 2",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/v-podzemele-ja-pojdu-tam-krasavicu-najdu-2.jpg"},

{"name":"В подземелье я пойду, там красавицу найду [ova-2]",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/v-podzemele-ja-pojdu-tam-krasavicu-najdu-[ova-2].jpg"},

{"name":"В подземелье я пойду, там красавицу найду 3",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/v-podzemele-ja-pojdu-tam-krasavicu-najdu-3.jpg"},

{"name":"В подземелье я пойду, там красавицу найду 4",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/v-podzemele-ja-pojdu-tam-krasavicu-najdu-4.jpg"},

{"name":"Врата Штэйна",
        "type":"Аниме",
        "serial":true,
        "during":true,
        "time":0,
        "url":"",
        "image":"../img/anime/vrata-shtejna.jpg"},

{"name":"Врата Штэйна 2",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/vrata-shtejna-2.jpg"},

{"name":"",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/"},

{"name":"",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/"},

{"name":"",
        "type":"Аниме",
        "serial":true,
        "during":false,
        "time":0,
        "url":"",
        "image":"../img/anime/"}
]